apiVersion: v1
data:
  password: VHhWZVE0bk44MlNTaVlIb3N3cU9VUlp2UURhTDRLcE5FbHNDRUVlOWJ3RHhNZDczS2NrSWVYelM1Y1U2TGlDMg==
  username: YXBw
kind: Secret
metadata:
  name: cluster-cnpg-restore-app-user
  namespace: cnpg
type: kubernetes.io/basic-auth
---
apiVersion: v1
data:
  password: dU4zaTFIaDBiWWJDYzRUeVZBYWNCaG1TemdxdHpxeG1PVmpBbjBRSUNoc0pyU211OVBZMmZ3MnE4RUtLTHBaOQ==
  username: cG9zdGdyZXM=
kind: Secret
metadata:
  name: cluster-cnpg-restore-superuser
  namespace: cnpg
type: kubernetes.io/basic-auth
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-cnpg-restore
  namespace: cnpg
spec:
  description: "This is a restore cluster"
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgis:15-3.3
  superuserSecret:
    name: cluster-cnpg-restore-superuser
  bootstrap:
    recovery:
      backup:
        name: backup-on-demand
  storage:
    size: 1Gi
    storageClass: standard
  backup:
    barmanObjectStore:
      destinationPath: "gs://cnpg-backups/cluster-cnpg-restore"
      googleCredentials:
        gkeEnvironment: true
  serviceAccountTemplate:
    metadata:
      annotations:
        iam.gke.io/gcp-service-account: cnpg@<project>.iam.gserviceaccount.com
  monitoring:
    enablePodMonitor: true